service: stream4

image: nwclouddev/stream4

servers:
  - media.nwclouddev.com

registry:
  username: nwclouddev
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    DB_HOST: media.nwclouddev.com
  secret:
    - RAILS_MASTER_KEY
    - SECRET_KEY_BASE
    - STREAM4_DATABASE_PASSWORD

ssh:
  user: deploy

builder:
  args:
    RUBY_VERSION: 3.3.4

  remote:
    arch: amd64

volumes:
  - /media/adam/NAS/Utility/content:/rails/public/content:rw

traefik:
  options:
    publish:
      - "443:443"
    args:
      entryPoints.websecure.address: ":443"