service: stream4

image: nwclouddev/stream4

servers:
  web:
    hosts: 
      - media.nwclouddev.com

registry:
  username: nwclouddev
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    DB_HOST: media.nwclouddev.com
  secret:
    - RAILS_MASTER_KEY
    - SECRET_KEY_BASE
    - STREAM4_DATABASE_PASSWORD

ssh:
  user: deploy

builder:
  args:
    RUBY_VERSION: 3.3.4
  remote:
    arch: amd64
    host: 10.10.0.15
    
volumes:
  - /home/adam/NAS/Utility/content:/rails/public/content:rw

# traefik:
#   options:
#     publish:
#       - "443:443"
#     # Make sure the file for this volume is set up on the host server
#     # and has the correct permissions.
#     volume:
#       - "/etc/letsencrypt/acme.json:/etc/letsencrypt/acme.json"
#   args:
#     entryPoints.web.address: ":80"
#     entryPoints.websecure.address: ":443"
#     entryPoints.web.http.redirections.entryPoint.to: websecure
#     entryPoints.web.http.redirections.entryPoint.scheme: https
#     entryPoints.web.http.redirections.entrypoint.permanent: true
#     certificatesResolvers.letsencrypt.acme.email: "adam@nwclouddev.com"
#     # Make sure the value for this argument matches the mounted file
#     # set in the `volume:` section for Traefik.
#     certificatesResolvers.letsencrypt.acme.storage: "/etc/letsencrypt/acme.json"
#     certificatesResolvers.letsencrypt.acme.httpchallenge: true
#     certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web